module Rex
module Post
module Meterpreter
module Extensions
module Mirv
TLV_TYPE_LUA_CODE = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 681)
TLV_TYPE_MIRV_LUA_RETMSG = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 682)
TLV_TYPE_MIRV_NEWTHREAD = TLV_META_TYPE_BOOL | (TLV_EXTENSIONS + 683)
TLV_TYPE_MIRV_RET_THREADID = TLV_META_TYPE_UINT     | (TLV_EXTENSIONS + 684)
TLV_TYPE_MIRV_THREADERR = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 685)
TLV_TYPE_MIRV_THREADLIST = TLV_META_TYPE_GROUP | (TLV_EXTENSIONS + 686)
TLV_TYPE_MIRV_THREADRECORD = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 687)
end
end
end
end
end