# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module Ocioralog

TLV_TYPE_OCIORALOG_HOOK       		= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 2)
TLV_TYPE_OCIORALOG_UNHOOK        	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 3)
TLV_TYPE_OCIORALOG_SETLOGFILE      	= TLV_META_TYPE_STRING| (TLV_EXTENSIONS + 4)
TLV_TYPE_OCIORALOG_GETLOGFILE    	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 5)
TLV_TYPE_OCIORALOG_HOOKOCISERVERATTACH 	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 6)
TLV_TYPE_OCIORALOG_HOOKOCISTMTEXECUTE 	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 7)
TLV_TYPE_OCIORALOG_HOOKOCIATTRSET 	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 8)
TLV_TYPE_OCIORALOG_UNHOOKOCISERVERATTACH 	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 9)
TLV_TYPE_OCIORALOG_UNHOOKOCISTMTEXECUTE 	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 10)
TLV_TYPE_OCIORALOG_UNHOOKOCIATTRSET 		= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 11)

TLV_TYPE_OCIORALOG_GENERIC_RESPONSE = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 12)

end
end
end
end
end
