# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module Keylogger

TLV_TYPE_EXTENSION_KEYLOGGER		= 0
TLV_TYPE_KEYLOGGER_STATUS		= TLV_META_TYPE_BOOL   | (TLV_TYPE_EXTENSION_KEYLOGGER + TLV_EXTENSIONS + 1)
TLV_TYPE_KEYLOGGER_CAPTURE_RECORD	= TLV_META_TYPE_GROUP  | (TLV_TYPE_EXTENSION_KEYLOGGER + TLV_EXTENSIONS + 2)
TLV_TYPE_KEYLOGGER_CAPTURE_RECORD_NAME	= TLV_META_TYPE_STRING | (TLV_TYPE_EXTENSION_KEYLOGGER + TLV_EXTENSIONS + 3)
TLV_TYPE_KEYLOGGER_CAPTURE_RECORD_DATA	= TLV_META_TYPE_RAW    | (TLV_TYPE_EXTENSION_KEYLOGGER + TLV_EXTENSIONS + 4)

end
end
end
end
end
