require 'msf/core/model/client'
require 'msf/core/model/host'
require 'msf/core/model/note'
require 'msf/core/model/ref'
require 'msf/core/model/service'
require 'msf/core/model/workspace'
require 'msf/core/model/vuln'

require 'msf/core/model/wmap_target'
require 'msf/core/model/wmap_request'