#!/usr/bin/env ruby
#
# $Id$
#
# Ruby front-end to the Armitage Java user interface
#
# $Revision$
#

msfbase = __FILE__
while File.symlink?(msfbase)
	msfbase = File.expand_path(File.readlink(msfbase), File.dirname(msfbase))
end

if RUBY_PLATFORM =~ /mswin|mingw/i
	exec "javaw", "-jar", "#{File.dirname(msfbase)}/data/armitage/armitage.jar", *ARGV
else
	exec "java", "-jar", "#{File.dirname(msfbase)}/data/armitage/armitage.jar", *ARGV
end
