services:
  ms:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        BUNDLER_ARGS: --jobs=8
    image: metasploit:dev
    environment:
      DATABASE_URL: postgres://postgres@db:5432/msf_dev?pool=100&timeout=5&reconnect=true&allow_concurrency=true
    volumes:
      - .:/usr/src/metasploit-framework
