#!/usr/bin/env ruby
# -*- coding: binary -*-
#
# $Id$
#
# Graphical user interface written in Java with rpc.
#
# $Revision$
#

msfbase = __FILE__
while File.symlink?(msfbase)
	msfbase = File.expand_path(File.readlink(msfbase), File.dirname(msfbase))
end

$:.unshift(File.expand_path(File.join(File.dirname(msfbase), 'lib')))
require 'fastlib'
require 'msfenv'

begin
	require 'msgpack'
rescue LoadError
	raise LoadError, "Missing msgpack gem, try 'gem install msgpack' to use MSFGui"
end

if RUBY_PLATFORM =~ /mswin|mingw/i
	exec "javaw -jar #{File.dirname(msfbase)}/data/gui/msfgui.jar"
else
	exec "java -jar #{File.dirname(msfbase)}/data/gui/msfgui.jar"
end
