#!/usr/bin/env ruby
#
# This is a basic user interface using the Gtk2 GUI library
#

msfbase = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
$:.unshift(File.join(File.dirname(msfbase), 'lib'))


require 'rex'
require 'msf/base'
require 'msf/ui'

# Check for ruby packages
begin
	require 'gtk2'
	require 'libglade2'
rescue ::Exception => e
	$stderr.puts "[*] The msfgui interface requires the ruby-gtk2 and ruby-libglade2 package"
	exit(0)
end

# Check for Gtk+ version
# Returns: nil if the GTK+ library is compatible with the given version, 
# or a string describing the version mismatch.
if gtkversion = Gtk.check_version(2,10,0)
	$stderr.puts "[*] The msfgui interface requires Gtk+ 2.10 or later"
	puts "Your Gtk+ version: #{gtkversion}"
	exit
end	

require 'msf/ui/gtk2'

# Declare the argument parser for msfgui
arguments = Rex::Parser::Arguments.new(
	"-v" => [ true,  "A number between 0 and 3 that controls log verbosity" ],
	"-d" => [ false, "Keep running in the foreground"                       ],
	"-h" => [ false, "Help banner"                                          ])

opts = {}
background = false

# Parse command line arguments.
arguments.parse(ARGV) { |opt, idx, val|
	case opt
		when "-v"
			opts['LogLevel'] = val
		when "-d"
			background = true
		when "-h"
			print(
				"\nUsage: msfgui <options>\n" +
				arguments.usage)
			exit
	end
}

exit if (Process.fork()) unless background == false

# Language is English
ENV['LANG'] = 'C'

# Create the driver instance and run it.
Msf::Ui::Gtk2::Driver.new(opts).run


