#!/usr/bin/env ruby
#
# This is a basic user interface using the Wx GUI library
#

$:.unshift(File.join(File.dirname(__FILE__), 'lib'))

require 'rex'
require 'msf/base'
require 'msf/ui'

begin
	require 'wxruby'
	require 'msf/ui/wx'
rescue ::Exception => e
	$stderr.puts "[*] The msfwx interface requires the wxruby package"
	exit(0)
end


# Declare the argument parser for msfwx
arguments = Rex::Parser::Arguments.new(
	"-v" => [ true,  "A number between 0 and 3 that controls log verbosity" ],
	"-d" => [ false, "Keep running in the foreground"                       ],
	"-h" => [ false, "Help banner"                                          ])

opts = {}
background = false

# Parse command line arguments.
arguments.parse(ARGV) { |opt, idx, val|
	case opt
		when "-v"
			opts['LogLevel'] = val
		when "-d"
			background = true
		when "-h"
			print(
				"\nUsage: msfwx <options>\n" +
				arguments.usage)
			exit
	end
}

exit if (Process.fork()) unless background == false

# Create the driver instance and run it.
Msf::Ui::Wx::Driver.new(opts).run
