#!/usr/bin/env ruby
#
# This user interface provides users with a command console interface to the
# framework.
#

msfbase = File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__
$:.unshift(File.join(File.dirname(msfbase), 'lib'))

msfroot = File.join(File.dirname(msfbase), 'data', 'msfweb')
Dir.chdir(msfroot)

msfserv = File.join('script', 'server')
system(msfserv, '-p', '55555', '-b', '127.0.0.1')

