module Rex
module Post
module Meterpreter
module Extensions
module Webcam

TLV_TYPE_WEBCAM_IMAGE = TLV_META_TYPE_RAW| (TLV_EXTENSIONS + 1)
TLV_TYPE_WEBCAM_INTERFACE_ID = TLV_META_TYPE_UINT| (TLV_EXTENSIONS + 2)
TLV_TYPE_WEBCAM_QUALITY = TLV_META_TYPE_UINT| (TLV_EXTENSIONS + 3)
TLV_TYPE_WEBCAM_NAME = TLV_META_TYPE_STRING| (TLV_EXTENSIONS + 4)
TLV_TYPE_WEBCAM_SOUND = TLV_META_TYPE_RAW| (TLV_EXTENSIONS + 5)

end
end
end
end
end