# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module Kiwi

TLV_TYPE_KIWI_PWD_ID        = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 1)
TLV_TYPE_KIWI_PWD_RESULT    = TLV_META_TYPE_GROUP  | (TLV_EXTENSIONS + 2)
TLV_TYPE_KIWI_PWD_USERNAME  = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 3)
TLV_TYPE_KIWI_PWD_DOMAIN    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 4)
TLV_TYPE_KIWI_PWD_PASSWORD  = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 5)
TLV_TYPE_KIWI_PWD_AUTH_HI   = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 6)
TLV_TYPE_KIWI_PWD_AUTH_LO   = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 7)
TLV_TYPE_KIWI_PWD_LMHASH    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 8)
TLV_TYPE_KIWI_PWD_NTLMHASH  = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 9)

TLV_TYPE_KIWI_GOLD_USER     = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 10)
TLV_TYPE_KIWI_GOLD_DOMAIN   = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 11)
TLV_TYPE_KIWI_GOLD_SID      = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 12)
TLV_TYPE_KIWI_GOLD_TGT      = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 13)
TLV_TYPE_KIWI_GOLD_TICKET   = TLV_META_TYPE_RAW    | (TLV_EXTENSIONS + 14)

end
end
end
end
end
