#!/usr/bin/env ruby
# -*- coding: binary -*-

module Rex
module Post
module Meterpreter
module Extensions
module Android

TLV_TYPE_SMS_ADDRESS        = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9001)
TLV_TYPE_SMS_BODY           = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9002)
TLV_TYPE_SMS_TYPE           = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9003)
TLV_TYPE_SMS_GROUP          = TLV_META_TYPE_GROUP   | (TLV_EXTENSIONS + 9004)
TLV_TYPE_SMS_STATUS         = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9005)
TLV_TYPE_SMS_DATE           = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9006)

TLV_TYPE_CONTACT_GROUP      = TLV_META_TYPE_GROUP   | (TLV_EXTENSIONS + 9007)
TLV_TYPE_CONTACT_NUMBER     = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9008)
TLV_TYPE_CONTACT_EMAIL      = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9009)
TLV_TYPE_CONTACT_NAME       = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9010)

TLV_TYPE_GEO_LAT            = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9011)
TLV_TYPE_GEO_LONG           = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9012)

TLV_TYPE_CALLLOG_NAME       = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9013)
TLV_TYPE_CALLLOG_TYPE       = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9014)
TLV_TYPE_CALLLOG_DATE       = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9015)
TLV_TYPE_CALLLOG_DURATION   = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9016)
TLV_TYPE_CALLLOG_GROUP      = TLV_META_TYPE_GROUP   | (TLV_EXTENSIONS + 9017)
TLV_TYPE_CALLLOG_NUMBER     = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9018)

TLV_TYPE_CHECK_ROOT_BOOL    = TLV_META_TYPE_BOOL    | (TLV_EXTENSIONS + 9019)

TLV_TYPE_SHUTDOWN_TIMER     = TLV_META_TYPE_UINT    | (TLV_EXTENSIONS + 9020)

TLV_TYPE_WHATSAPP_ENCRYPTED = TLV_META_TYPE_RAW     | (TLV_EXTENSIONS + 9022);
TLV_TYPE_WHATSAPP_RAW       = TLV_META_TYPE_RAW     | (TLV_EXTENSIONS + 9024);
TLV_TYPE_WHATSAPP_ENUM_MSG  = TLV_META_TYPE_UINT    | (TLV_EXTENSIONS + 9026);
TLV_TYPE_WHATSAPP_ENUM_PP   = TLV_META_TYPE_UINT    | (TLV_EXTENSIONS + 9027);
TLV_TYPE_WHATSAPP_ENUM_VOI  = TLV_META_TYPE_UINT    | (TLV_EXTENSIONS + 9028);
TLV_TYPE_WHATSAPP_ENUM_VID  = TLV_META_TYPE_UINT    | (TLV_EXTENSIONS + 9029);
TLV_TYPE_WHATSAPP_ENUM_IMG  = TLV_META_TYPE_UINT    | (TLV_EXTENSIONS + 9030);
TLV_TYPE_WHATSAPP_ENUM_AUD  = TLV_META_TYPE_UINT    | (TLV_EXTENSIONS + 9031);
TLV_TYPE_WHATSAPP_STRING    = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9032);
TLV_TYPE_WHATSAPP_REQUEST   = TLV_META_TYPE_STRING  | (TLV_EXTENSIONS + 9033);
TLV_TYPE_WHATSAPP_GROUP     = TLV_META_TYPE_GROUP   | (TLV_EXTENSIONS + 9034);


end; end; end; end; end
