# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module Extapi

# ID for the extension (needs to be a multiple of 1000)
EXTENSION_ID_EXTAPI = 3000

# Associated command ids
COMMAND_ID_EXTAPI_ADSI_DOMAIN_QUERY        = EXTENSION_ID_EXTAPI + 1
COMMAND_ID_EXTAPI_CLIPBOARD_GET_DATA       = EXTENSION_ID_EXTAPI + 2
COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_DUMP   = EXTENSION_ID_EXTAPI + 3
COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_PAUSE  = EXTENSION_ID_EXTAPI + 4
COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_PURGE  = EXTENSION_ID_EXTAPI + 5
COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_RESUME = EXTENSION_ID_EXTAPI + 6
COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_START  = EXTENSION_ID_EXTAPI + 7
COMMAND_ID_EXTAPI_CLIPBOARD_MONITOR_STOP   = EXTENSION_ID_EXTAPI + 8
COMMAND_ID_EXTAPI_CLIPBOARD_SET_DATA       = EXTENSION_ID_EXTAPI + 9
COMMAND_ID_EXTAPI_NTDS_PARSE               = EXTENSION_ID_EXTAPI + 10
COMMAND_ID_EXTAPI_PAGEANT_SEND_QUERY       = EXTENSION_ID_EXTAPI + 11
COMMAND_ID_EXTAPI_SERVICE_CONTROL          = EXTENSION_ID_EXTAPI + 12
COMMAND_ID_EXTAPI_SERVICE_ENUM             = EXTENSION_ID_EXTAPI + 13
COMMAND_ID_EXTAPI_SERVICE_QUERY            = EXTENSION_ID_EXTAPI + 14
COMMAND_ID_EXTAPI_WINDOW_ENUM              = EXTENSION_ID_EXTAPI + 15
COMMAND_ID_EXTAPI_WMI_QUERY                = EXTENSION_ID_EXTAPI + 16

end
end
end
end
end
