# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module Incognito

# ID for the extension (needs to be a multiple of 1000)
EXTENSION_ID_INCOGNITO = 12000

# Associated command ids
COMMAND_ID_INCOGNITO_ADD_GROUP_USER      = EXTENSION_ID_INCOGNITO + 1
COMMAND_ID_INCOGNITO_ADD_LOCALGROUP_USER = EXTENSION_ID_INCOGNITO + 2
COMMAND_ID_INCOGNITO_ADD_USER            = EXTENSION_ID_INCOGNITO + 3
COMMAND_ID_INCOGNITO_IMPERSONATE_TOKEN   = EXTENSION_ID_INCOGNITO + 4
COMMAND_ID_INCOGNITO_LIST_TOKENS         = EXTENSION_ID_INCOGNITO + 5
COMMAND_ID_INCOGNITO_SNARF_HASHES        = EXTENSION_ID_INCOGNITO + 6

TLV_TYPE_INCOGNITO_LIST_TOKENS_DELEGATION        	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 2)
TLV_TYPE_INCOGNITO_LIST_TOKENS_IMPERSONATION        	= TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 3)
TLV_TYPE_INCOGNITO_LIST_TOKENS_ORDER       	= TLV_META_TYPE_UINT| (TLV_EXTENSIONS + 4)
TLV_TYPE_INCOGNITO_IMPERSONATE_TOKEN    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 5)
TLV_TYPE_INCOGNITO_GENERIC_RESPONSE    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 6)
TLV_TYPE_INCOGNITO_USERNAME    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 7)
TLV_TYPE_INCOGNITO_PASSWORD    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 8)
TLV_TYPE_INCOGNITO_SERVERNAME    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 9)
TLV_TYPE_INCOGNITO_GROUPNAME    = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 10)

end
end
end
end
end
