# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module Lanattacks

# ID for the extension (needs to be a multiple of 1000)
EXTENSION_ID_LANATTACKS = 15000

# Associated command ids
COMMAND_ID_LANATTACKS_ADD_TFTP_FILE   = EXTENSION_ID_LANATTACKS + 1
COMMAND_ID_LANATTACKS_DHCP_LOG        = EXTENSION_ID_LANATTACKS + 2
COMMAND_ID_LANATTACKS_RESET_DHCP      = EXTENSION_ID_LANATTACKS + 3
COMMAND_ID_LANATTACKS_RESET_TFTP      = EXTENSION_ID_LANATTACKS + 4
COMMAND_ID_LANATTACKS_SET_DHCP_OPTION = EXTENSION_ID_LANATTACKS + 5
COMMAND_ID_LANATTACKS_START_DHCP      = EXTENSION_ID_LANATTACKS + 6
COMMAND_ID_LANATTACKS_START_TFTP      = EXTENSION_ID_LANATTACKS + 7
COMMAND_ID_LANATTACKS_STOP_DHCP       = EXTENSION_ID_LANATTACKS + 8
COMMAND_ID_LANATTACKS_STOP_TFTP       = EXTENSION_ID_LANATTACKS + 9

TLV_TYPE_LANATTACKS_OPTION      = TLV_META_TYPE_RAW    | (TLV_EXTENSIONS + 1)
TLV_TYPE_LANATTACKS_OPTION_NAME = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 2)
TLV_TYPE_LANATTACKS_UINT        = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 3)
TLV_TYPE_LANATTACKS_RAW         = TLV_META_TYPE_RAW    | (TLV_EXTENSIONS + 4)

end
end
end
end
end
