# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module Priv

# ID for the extension (needs to be a multiple of 1000)
EXTENSION_ID_PRIV = 2000

# Associated command ids
COMMAND_ID_PRIV_ELEVATE_GETSYSTEM          = EXTENSION_ID_PRIV + 1
COMMAND_ID_PRIV_FS_BLANK_DIRECTORY_MACE    = EXTENSION_ID_PRIV + 2
COMMAND_ID_PRIV_FS_BLANK_FILE_MACE         = EXTENSION_ID_PRIV + 3
COMMAND_ID_PRIV_FS_GET_FILE_MACE           = EXTENSION_ID_PRIV + 4
COMMAND_ID_PRIV_FS_SET_FILE_MACE           = EXTENSION_ID_PRIV + 5
COMMAND_ID_PRIV_FS_SET_FILE_MACE_FROM_FILE = EXTENSION_ID_PRIV + 6
COMMAND_ID_PRIV_PASSWD_GET_SAM_HASHES      = EXTENSION_ID_PRIV + 7

# Passwd
TLV_TYPE_SAM_HASHES                 = TLV_META_TYPE_STRING | (TLV_EXTENSIONS +   1)

# Fs
TLV_TYPE_FS_FILE_MODIFIED           = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 100)
TLV_TYPE_FS_FILE_ACCESSED           = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 101)
TLV_TYPE_FS_FILE_CREATED            = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 102)
TLV_TYPE_FS_FILE_EMODIFIED          = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 103)
TLV_TYPE_FS_FILE_PATH               = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 110)
TLV_TYPE_FS_SRC_FILE_PATH           = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 111)

# Elevate
TLV_TYPE_ELEVATE_TECHNIQUE          = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 200)
TLV_TYPE_ELEVATE_SERVICE_NAME       = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 201)
TLV_TYPE_ELEVATE_SERVICE_DLL        = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 202)
TLV_TYPE_ELEVATE_SERVICE_LENGTH     = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 203)

end
end
end
end
end
