# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module Powershell

# ID for the extension (needs to be a multiple of 1000)
EXTENSION_ID_POWERSHELL = 14000

# Associated command ids
COMMAND_ID_POWERSHELL_ASSEMBLY_LOAD  = EXTENSION_ID_POWERSHELL + 1
COMMAND_ID_POWERSHELL_EXECUTE        = EXTENSION_ID_POWERSHELL + 2
COMMAND_ID_POWERSHELL_SESSION_REMOVE = EXTENSION_ID_POWERSHELL + 3
COMMAND_ID_POWERSHELL_SHELL          = EXTENSION_ID_POWERSHELL + 4

TLV_TYPE_POWERSHELL_SESSIONID        = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 1)
TLV_TYPE_POWERSHELL_CODE             = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 2)
TLV_TYPE_POWERSHELL_RESULT           = TLV_META_TYPE_STRING | (TLV_EXTENSIONS + 3)
TLV_TYPE_POWERSHELL_ASSEMBLY_SIZE    = TLV_META_TYPE_UINT   | (TLV_EXTENSIONS + 4)
TLV_TYPE_POWERSHELL_ASSEMBLY         = TLV_META_TYPE_RAW    | (TLV_EXTENSIONS + 5)

end
end
end
end
end
