#
# The type set that encoders can fall within.  This classifies the type of
# output generated by the encoder in terms of the general character set
# that is used as well as other potential attributes.
#
module Msf::Encoder::Type
  #
  # 'A' - 'Z', '0' - '9'
  #
  AlphanumUpper        = "alpha_upper"
  #
  # 'a' - 'z', 'A' - 'Z', '0' - '9'
  #
  AlphanumMixed        = "alpha_mixed"
  #
  # Unicode-safe 'A' - 'Z', '0' - '9'
  #
  AlphanumUnicodeUpper = "alpha_unicode_upper"
  #
  # Unicode-safe 'a' - 'z', 'A' - 'Z', '0' - '9'
  #
  AlphanumUnicodeMixed = "alpha_unicode_mixed"
  #
  # toupper/tolower safe ascii - not 'a' - 'z', 'A' - 'Z'
  #
  NonAlpha = "non_alpha"
  #
  # tolower safe ascii - not 'A' - 'Z' (more flexable than nonalpha)
  #
  NonUpper = "non_upper"
  #
  # tolower safe ascii UTF8-safe (<= 0x7f only)
  #
  NonUpperUtf8Safe = "non_upper_utf8_safe"
  #
  # tolower safe underscore safe for CVE-2012-2329 - PHP CGI apache_request_headers bof
  #
  NonUpperUnderscoreSafe = "non_upper_underscore"
  #
  # May result in the generation of any characters
  #
  Unspecified = "unspecified"
  #
  # The raw payload passed to the encoder will be the same as the encoded
  # payload
  #
  Raw = "raw"
  #
  # Special Single Static Bit encoder
  #
  SingleStaticBit = "single_static_bit"
  #
  # Special printf(1) via PHP magic_quotes Command Encoder
  #
  PrintfPHPMagicQuotes = "printf_php_mq"
end