# -*- coding: binary -*-
# CorrM @ fb.me/IslamNofl

module Rex
module Post
module Meterpreter
module Extensions
module AppApi

# ID for the extension (needs to be a multiple of 1000)
EXTENSION_ID_APPAPI = 9000

# Associated command ids
COMMAND_ID_APPAPI_APP_INSTALL   = EXTENSION_ID_APPAPI + 1
COMMAND_ID_APPAPI_APP_LIST      = EXTENSION_ID_APPAPI + 2
COMMAND_ID_APPAPI_APP_RUN       = EXTENSION_ID_APPAPI + 3
COMMAND_ID_APPAPI_APP_UNINSTALL = EXTENSION_ID_APPAPI + 4

##
#
# Apps
#
##

TLV_TYPE_APPS_LIST          = TLV_META_TYPE_STRING   | (TLV_EXTENSIONS + 2911)
TLV_TYPE_APPS_LIST_OPT      = TLV_META_TYPE_UINT     | (TLV_EXTENSIONS + 2912)

TLV_TYPE_APP_PACKAGE_NAME   = TLV_META_TYPE_STRING   | (TLV_EXTENSIONS + 2913)
TLV_TYPE_APP_APK_PATH       = TLV_META_TYPE_STRING   | (TLV_EXTENSIONS + 2914)
TLV_TYPE_APP_ENUM           = TLV_META_TYPE_UINT     | (TLV_EXTENSIONS + 2915)

TLV_TYPE_APP_RUN_ENUM       = TLV_META_TYPE_UINT     | (TLV_EXTENSIONS + 2916)


end; end; end; end; end

