# Default values for meterpreter.

#The IP Address the payload will connect to
lhost:
#The Port meterpreter will connect to
lport:

image:
  repository: metasploitframework/metasploit-framework
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Tune the privileges your Kubernetes meterpreter will run with
privileges:
  # Disable Kubernetes API Server Access - even to the discovery APIs
  useServiceAccount: true
  # Run Metasploit framework as Kubernetes cluster admin (useServiceAccount must be true for this setting to be effective)
  bindClusterRole: "" #cluster-admin

  #
  # Privileges related to node hosting metasploit Pod
  # See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  podSecurityContext: {}
    # fsGroup: 2000
  # Metasploit container security context
  securityContext: {}
    #allowPrivilegeEscalation: false
    # capabilities:
    #   add:
    #   - NET_BIND_SERVICE
    #   drop:
    #   - all
    #runAsNonRoot: true
    #runAsUser: 1000
    #runAsGroup: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
