# -*- coding: binary -*-
module Rex
module Post
module Meterpreter
module Extensions
module NetworkPug

# ID for the extension (needs to be a multiple of 1000)
EXTENSION_ID_NETWORKPUG = 6000

# Associated command ids
COMMAND_ID_NETWORKPUG_START = EXTENSION_ID_NETWORKPUG + 1
COMMAND_ID_NETWORKPUG_STOP  = EXTENSION_ID_NETWORKPUG + 2

TLV_TYPE_EXTENSION_NETWORKPUG	= 0
TLV_TYPE_NETWORKPUG_INTERFACE	= TLV_META_TYPE_STRING | (TLV_TYPE_EXTENSION_NETWORKPUG + TLV_EXTENSIONS + 1)
TLV_TYPE_NETWORKPUG_FILTER	= TLV_META_TYPE_STRING | (TLV_TYPE_EXTENSION_NETWORKPUG + TLV_EXTENSIONS + 2)

end
end
end
end
end
