# -*- coding: binary -*-

module Rex
module Post
module Meterpreter

# Effectively maps to the number of commands an extension can
# have. Each extension ID starts at a range boundary and is used
# to identify extensions.
COMMAND_ID_RANGE = 1000

# ID for the extension (needs to be a multiple of 1000)
EXTENSION_ID_CORE = 0

COMMAND_ID_CORE_CHANNEL_CLOSE            = EXTENSION_ID_CORE + 1
COMMAND_ID_CORE_CHANNEL_EOF              = EXTENSION_ID_CORE + 2
COMMAND_ID_CORE_CHANNEL_INTERACT         = EXTENSION_ID_CORE + 3
COMMAND_ID_CORE_CHANNEL_OPEN             = EXTENSION_ID_CORE + 4
COMMAND_ID_CORE_CHANNEL_READ             = EXTENSION_ID_CORE + 5
COMMAND_ID_CORE_CHANNEL_SEEK             = EXTENSION_ID_CORE + 6
COMMAND_ID_CORE_CHANNEL_TELL             = EXTENSION_ID_CORE + 7
COMMAND_ID_CORE_CHANNEL_WRITE            = EXTENSION_ID_CORE + 8
COMMAND_ID_CORE_CONSOLE_WRITE            = EXTENSION_ID_CORE + 9
COMMAND_ID_CORE_ENUMEXTCMD               = EXTENSION_ID_CORE + 10
COMMAND_ID_CORE_GET_SESSION_GUID         = EXTENSION_ID_CORE + 11
COMMAND_ID_CORE_LOADLIB                  = EXTENSION_ID_CORE + 12
COMMAND_ID_CORE_MACHINE_ID               = EXTENSION_ID_CORE + 13
COMMAND_ID_CORE_MIGRATE                  = EXTENSION_ID_CORE + 14
COMMAND_ID_CORE_NATIVE_ARCH              = EXTENSION_ID_CORE + 15
COMMAND_ID_CORE_NEGOTIATE_TLV_ENCRYPTION = EXTENSION_ID_CORE + 16
COMMAND_ID_CORE_PATCH_URL                = EXTENSION_ID_CORE + 17
COMMAND_ID_CORE_PIVOT_ADD                = EXTENSION_ID_CORE + 18
COMMAND_ID_CORE_PIVOT_REMOVE             = EXTENSION_ID_CORE + 19
COMMAND_ID_CORE_PIVOT_SESSION_DIED       = EXTENSION_ID_CORE + 20
COMMAND_ID_CORE_SET_SESSION_GUID         = EXTENSION_ID_CORE + 21
COMMAND_ID_CORE_SET_UUID                 = EXTENSION_ID_CORE + 22
COMMAND_ID_CORE_SHUTDOWN                 = EXTENSION_ID_CORE + 23
COMMAND_ID_CORE_TRANSPORT_ADD            = EXTENSION_ID_CORE + 24
COMMAND_ID_CORE_TRANSPORT_CHANGE         = EXTENSION_ID_CORE + 25
COMMAND_ID_CORE_TRANSPORT_GETCERTHASH    = EXTENSION_ID_CORE + 26
COMMAND_ID_CORE_TRANSPORT_LIST           = EXTENSION_ID_CORE + 27
COMMAND_ID_CORE_TRANSPORT_NEXT           = EXTENSION_ID_CORE + 28
COMMAND_ID_CORE_TRANSPORT_PREV           = EXTENSION_ID_CORE + 29
COMMAND_ID_CORE_TRANSPORT_REMOVE         = EXTENSION_ID_CORE + 30
COMMAND_ID_CORE_TRANSPORT_SETCERTHASH    = EXTENSION_ID_CORE + 31
COMMAND_ID_CORE_TRANSPORT_SET_TIMEOUTS   = EXTENSION_ID_CORE + 32
COMMAND_ID_CORE_TRANSPORT_SLEEP          = EXTENSION_ID_CORE + 33
COMMAND_ID_CORE_PIVOT_SESSION_NEW        = EXTENSION_ID_CORE + 34

end
end
end
